### ISSUE TITLE
host network via docker-compose?

### ISSUE THREAD

**Issue by karl0ss** [linuxserver/docker-tvheadend#133]
I have setup this image using docker-compose and what i beleive to be host network 

```
 tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    network_mode: host
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - RUN_OPTS=run options here #optional
    volumes:
      - ${DOCKERCONFDIR}/tvheadend:/config
      - /mnt/Other_Stuff/DVRecordings:/recordings
    restart: unless-stopped
```

But I am unable to connect to connect on 9981, when I look in portainer there are no ports mapped, so I guess that makes sense, but you say to remove the port mappings so I did that...

Sure im just doing something stupid...

thanks
