### ISSUE TITLE
Picons are outdated

### ISSUE THREAD

**Issue by bistory** [linuxserver/docker-tvheadend#140]
Hi !

First thanks for this great docker image !

I'm playing with picons. However the package that is downloading during setup is outdated. Thus some logos are missing (mostly because they are now in HD so they contains HD in the channel name).

I don't know where you found the archive file and I don't see any correspondance with the ones that are provided on the Picons' github so I can't make a PR :(

Could you please look if it's possible to find more recent archives ?

Thanks !

**Comment by j0nnymoe** [comment]
We build our own picons package on a weekly basis (https://ci.linuxserver.io/job/Xtras-Builders-Etc/job/picons-builder/) which the docker container pulls in during build (https://github.com/linuxserver/docker-tvheadend/blob/master/Dockerfile#L325).

Have you recently updated your container?

**Comment by bistory** [comment]
I installed it yesterday, so it brand new ;-)

I downloaded the archive before opening the issue : here are some of the channels that are missing : 

- 13emeruehd
- clubrtlhd
- plugrtlhd
- france2hd
- abxplore (missing on picons)
- artebelgiquehd

And so on, it seems that the "HD" is always missing from the file names...

**Comment by tobbenb** [comment]
We clone master branch from picons github, so it might be something with the build that is not working as it should. Will have to look at it, but might take some time.

**Comment by CHBMB** [comment]
Just taking a look at this, our picons were last build successfully 6 days ago and I'm running the build locally and it's working.

@bistory What version of TVHeadend are you running?  Can you post your docker run/compose command please?

**Comment by CHBMB** [comment]
Our Master TVHeadend branch was build 7 days ago, so won't have picked up the latest picons build, and our 4.32 branch was last built 27 days ago.  

However none of that is valid if you say you downloaded the archive we use and checked manually as that is only 6 days old.

Have you confirmed these icons are available in [picons master?](https://github.com/picons/picons)

**Comment by bistory** [comment]
@CHBMB here is the docker compose file :

```

---
version: "2"
services:
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=112
      - PGID=116
      - TZ=Europe/Brussels
    volumes:
      - /home/hts/.hts/config:/config
      - /media/71625484-9445-43c2-b433-876b74be6067/shared-files/Records:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dvb:/dev/dvb
    restart: unless-stopped
```

The archive I downloaded is the one mentioned in the Dockerfile : https://lsio-ci.ams3.digitaloceanspaces.com/picons/picons.tar.bz2

I made a review of all files in picons' master I found what is wrong : the snp.index file doesn't contain HD variants I mentioned earlier while they have logos and srp.index contains them :-)

I will open an issue on Picons !

Thanks for helping on this issue !
