### ISSUE TITLE
wrong time

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-tvheadend#142]
i run your wnderful dockerimage. Works fine.
but tvheadend has the wrong timezone date setting

i use the environment setting ind docker compose
when i run "date" as a command inside the container - the time is correct.
![grafik](https://user-images.githubusercontent.com/3322071/65980323-6becf800-e466-11e9-9fc9-2814841265bd.png)
But tvheadend seems to has its own time 
![grafik](https://user-images.githubusercontent.com/3322071/65980165-20d2e500-e466-11e9-95b2-42cfa72ca204.png)

**Comment by j0nnymoe** [comment]
Did you set the timezone within tvheadend itself?

**Comment by Gutz-Pilz** [comment]
I feel stupid for this question.
But where to set it?

**Comment by Gutz-Pilz** [comment]
i set it in the networksettings to local servertime, deleted epggrap.v3 and restarted the docker.
still the same time

**Comment by j0nnymoe** [comment]
What's your docker run command?

**Comment by Gutz-Pilz** [comment]
```
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    ports:
      - '9981:9981'
      - '9982:9982'
    network_mode: host
    volumes:
      - '/blabla/.tvheadend:/config'
      - '/blabla:/recordings'
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    restart: always
```
