### ISSUE TITLE
Tuners not found after commit from Oct. 2nd

### ISSUE THREAD

**Issue by bernhardberger** [linuxserver/docker-tvheadend#146]
This commit (https://github.com/linuxserver/docker-tvheadend/commit/70b794cabc48b805a746f31dc3a7ff03d148eae8) seeems to break the detection of my tuners. Is there any way I can help to debug this?

I mount
`/dev/dri` and
`/dev/dvb`

into the container (DD MaxS8 on an Ubuntu 18.04 Server, upgraded from ebb09680-ls35). ls36 and beyond seems to be broken for me (TVH can't find any tuners anymore) and the only change between ls35 and ls36 seems to be this commit.

**Comment by thelamer** [comment]
output of ```docker exec tvheadend ls -l /dev/dri /dev/dvb``` please

**Comment by bernhardberger** [comment]
`bberger@dexter:~/dexter$ docker exec tvheadend ls -l /dev/dri /dev/dvb
/dev/dri:
total 0
crw-rw---- 1 root video 226,   0 Oct 19 17:33 card0
crw-rw---- 1 root video 226, 128 Oct 19 17:33 renderD128

/dev/dvb:
total 0
drwxr-xr-x 2 root root 120 Oct 19 17:33 adapter0
drwxr-xr-x 2 root root 120 Oct 19 17:33 adapter1
drwxr-xr-x 2 root root 120 Oct 19 17:33 adapter2
drwxr-xr-x 2 root root 120 Oct 19 17:33 adapter3
drwxr-xr-x 2 root root 120 Oct 19 17:33 adapter4
drwxr-xr-x 2 root root 120 Oct 19 17:33 adapter5
drwxr-xr-x 2 root root 120 Oct 19 17:33 adapter6
drwxr-xr-x 2 root root 120 Oct 19 17:33 adapter7
`

**Comment by thelamer** [comment]
Yeah we specifically ignore root and only add to it's group if everything is owned by root as there are security implications with that. 

What distro are you running ? I believe Udev default should be setting the DVB device to video group.

**Comment by aptalca** [comment]
Do you have a startup script that modifies the dvb permissions?

**Comment by bernhardberger** [comment]
Vanilla Ubuntu 18.04 server with docker from the docker-ce repos.

Also running the default kernel drivers for the DD card.

linuxserver.io is the only image that /dev/dvb is mounted to.

**Comment by bernhardberger** [comment]
Just changed the permissions to root:video on /dev/dvb and tried upgrading to the :latest tag again, now TVH startup fails with the following error:
```
2019-10-19 17:59:15.353 [  ERROR] config: command '/bin/tar cjf /config/backup/4.3-1804~gebb096804.tar.bz2 --exclude backup --exclude epggrab/*.sock --exclude timeshift/buffer --exclude imagecache/meta --exclude imagecache/data .' returned error code 2
2019-10-19 17:59:15.353 [  ERROR] config: executed in directory '/config'
2019-10-19 17:59:15.353 [  ERROR] config: please DON'T report this as an error, you may use --nobackup to skip
2019-10-19 17:59:15.353 [  ERROR] config: ... or run the above command in the printed directory
2019-10-19 17:59:15.353 [  ERROR] config: ... using the same user/group as for the Tvheadend executable
2019-10-19 17:59:15.353 [  ERROR] config: ... to check the reason for the unfinished backup
2019-10-19 17:59:15.353 [  ERROR] config: backup: fatal error
```

**Comment by thelamer** [comment]
Default Udev rules in Ubuntu 18.04 are for DVB devices to be group owned by video: 
https://bazaar.launchpad.net/~ubuntu-core-dev/udev/ubuntu/view/head:/rules/rules.d/50-udev-default.rules#L48

Is this a USB device by chance? That might change things as far as perms go.

**Comment by bernhardberger** [comment]
No, it's an 8 Tuner PCIe card from Digital Devices (Max S8)

**Comment by bernhardberger** [comment]
PS: changing the permissions to `root:video` doesn't solve the issue. Still present in -ls36 and :latest

**Comment by aptalca** [comment]
@bernhardberger please do
`docker exec tvheadend ls -l /dev/dvb/adapter0`

and also post the command you used to create your container

**Comment by bernhardberger** [comment]
```bash
berger@dexter:~/dexter$ docker exec tvheadend ls -l /dev/dvb/adapter0
total 0
crw-rw---- 1 root video 212, 0 Oct 19 18:08 demux0
crw-rw---- 1 root video 212, 1 Oct 19 18:08 dvr0
crw-rw---- 1 root video 212, 3 Oct 19 18:08 frontend0
crw-rw---- 1 root video 212, 2 Oct 19 18:08 net0
```

docker-compose (v2):
```yml
  tvheadend:
    image: linuxserver/tvheadend:ebb09680-ls35
#    image: linuxserver/tvheadend:84c989e1-ls39
#    image: linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - /srv/tvheadend/config:/config
      - /mnt/storage/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    labels:
      - traefik.enable=true
      - traefik.port=9981
      - traefik.frontend.rule=Host:tvheadend.home.bernhardberger.at
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    restart: unless-stopped
```

**Comment by bernhardberger** [comment]
```bash
bberger@dexter:~/dexter$ docker exec tvheadend ls -l /dev/dvb/adapter0
total 0
crw-rw---- 1 root video 212, 0 Oct 19 18:08 demux0
crw-rw---- 1 root video 212, 1 Oct 19 18:08 dvr0
crw-rw---- 1 root video 212, 3 Oct 19 18:08 frontend0
crw-rw---- 1 root video 212, 2 Oct 19 18:08 net0
```

docker-compose (v2):
```yml
  tvheadend:
    image: linuxserver/tvheadend:ebb09680-ls35
#    image: linuxserver/tvheadend:84c989e1-ls39
#    image: linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - /srv/tvheadend/config:/config
      - /mnt/storage/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    labels:
      - traefik.enable=true
      - traefik.port=9981
      - traefik.frontend.rule=Host:****REDACTED****
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    restart: unless-stopped
```
