### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by aegie** [linuxserver/docker-tvheadend#153]
Hello, I'm having issues with this specific container. I am not new to docker, I use all my images from linuxserver, but this one is really problematic.

I tried with and without reverse proxy, but I cannot connect to the interface.

This is my part of my docker compose

```
tvheadend:
    depends_on:
      - ReverseProxy 
    image: linuxserver/tvheadend
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Bucharest
      - PUID=1001
      - PGID=100
      #- RUN_OPTS="--http_root /tv"
    volumes:
      - /sharedfolders/mediatools/tvheadend:/config
      - /sharedfolders/Media/RECORDINGS:/recordings
    ports:
      - 9981:9981
      - 9982:9982
    devices:
      - /dev/dri:/dev/dri #optional
      #- /dev/dvb:/dev/dvb #optional
    container_name: tvheadend
```

These are the logs:

![Clipboard01](https://user-images.githubusercontent.com/30295068/71717130-b728f500-2e1f-11ea-8193-fe9a0181ed52.jpg)
![Clipboard012](https://user-images.githubusercontent.com/30295068/71717134-babc7c00-2e1f-11ea-9632-cdfcb24b01bb.jpg)

All other containers are working as they should. As said, I also tried with the reverse proxy (added the args - RUN_OPTS="--http_root /tv" to specify the alternative http webroot, otherwise I got a 502 bad gateway) this was my conf, but here I got the error with "Welcome to Nginx!" blank page:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name tvheadend.*;

    include /config/nginx/ssl.conf;

    location /tv {
        include /config/nginx/proxy.conf;
	resolver 127.0.0.11 valid=30s;
        set $upstream_tvheadend tvheadend;
	proxy_pass http://192.168.1.151:9981;
		
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
    }
}
```

Any suggestions? Thank you! I googled everything, no solution for me.
