### ISSUE TITLE
[mod-init] Curl/JQ was not found on this system for Docker mods installing

### ISSUE THREAD

**Issue by tuxiano** [linuxserver/docker-tvheadend#192]
I'm trying to enable the crond in the tvh docker image, so download xmltv data on a daily basis. To achieve this, I'm trying to enable the cron Docker MOD, but the installation files, because Curl/JQ is missing.

`[mod-init] Curl/JQ was not found on this system for Docker mods installing`

Docker MOD: https://github.com/linuxserver/docker-mods/tree/universal-cron

## Expected Behavior
I'm expecting that the docker mod enables the crond after booting the docker image.

## Current Behavior
Installation of the docker mod fails. Crond is not running

## Steps to Reproduce
1. create a docker-compose.yml
2. Create a container app through the container station interface
3. Log into the container
4. See that the crond is not running

## Environment
**OS:** Qnap OS 5.0.0.1932
**CPU architecture:** x86_64
**How docker service was installed:**
I installed docker through the official Qnap App: Container station

## Command used to create docker container (run/create/compose/screenshot)
docker-compose.yml

```
version: "2.1"
services:
  tvheadend:
    image: lscr.io/linuxserver/tvheadend
    container_name: tvheadend
    # command: /usr/sbin/crond
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-cron
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 9981:9981
      - 9982:9982
    restart: unless-stopped
```

## Docker logs

```
mod-init] Curl/JQ was not found on this system for Docker mods installing
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)
ERROR: unable to select packages:
  jq (no such package):
    required by: world[jq]
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:universal-cron files to container
/docker-mods: line 102: jq: command not found
/docker-mods: line 35: jq: command not found

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

```
