### ISSUE TITLE
[BUG] XMLTV - tv_grab_zz_sdjson can't determine local timezone

### ISSUE THREAD

**Issue by raccettura** [linuxserver/docker-tvheadend#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```2023-07-06 01:37:35.592 spawn: Cannot determine local time zone
2023-07-06 01:37:35.602 xmltv: /usr/bin/tv_grab_zz_sdjson: no output detected
2023-07-06 01:37:35.602 xmltv: /usr/bin/tv_grab_zz_sdjson: grab returned no data
```

### Expected Behavior

Timezone should be set via:
```
export TZ=Timezone
```

### Steps To Reproduce

1. Setup XMLTV
2. Try and run

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```yaml
  tvheadend:
    image: linuxserver/tvheadend
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Americas/New_York
#      - RUN_OPTS=<run options here> #optional
    volumes:
      - ./data/tvheadend/config:/config
      - ./data/tvheadend/.xmltv:/.xmltv
      - /mnt/video/:/recordings
    labels:
     - "autoheal=true"
    ports:
      - 9981:9981
      - 9982:9982
    network_mode: host
    devices:
      - /dev/dri:/dev/dri #optional
    restart: unless-stopped

```

### Container logs

```bash
.
```
