### ISSUE TITLE
Not reachable by clients

### ISSUE THREAD

**Issue by LordVoodoo** [linuxserver/docker-tvheadend#88]
Hello,

I am running the docker-image linuxserver/tvheadend in my local network.

Settings are:

```
  tvserver:
    image: linuxserver/tvheadend
    container_name: tvserver
    restart: always
    ports:
      - "554:554"
      - "9981:9981"
      - "9982:9982"
      - "9983:9983"
    expose:
      - "9981"
      - "9982"
      - "9983"
      - "554"
    devices:
      - /dev/dri
    volumes:
      - "./tvheadend/config/:/config"
      - "./tvheadend/recordings:/recordings"
    network_mode: host   # used for HDHomerun
    environment:
      - TZ=Europe/Berlin
      - PGID=1000
      - PUID=1000
```
I can access the WebGui on Port 9981, but no TVHeadend client software on Windows or iOS lists the server.

Any idea?
